milter: $(SAPI_MILTER_PATH)

$(SAPI_MILTER_PATH): $(JONJ_GLOBAL_OBJS) $(JONJ_BINARY_OBJS) $(JONJ_MILTER_OBJS)
	$(BUILD_MILTER)

install-milter: $(SAPI_MILTER_PATH)
	@$(INSTALL) -m 0755 $(SAPI_MILTER_PATH) $(INSTALL_ROOT)$(bindir)/jonj-milter

