/* automatically generated by configure */
/* edit configure.in to change version number */
#define JONJ_MAJOR_VERSION 5
#define JONJ_MINOR_VERSION 6
#define JONJ_RELEASE_VERSION 36
#define JONJ_EXTRA_VERSION ""
#define JONJ_VERSION "5.6.36"
#define JONJ_VERSION_ID 50636
