#! /bin/sh
if test $# -lt 2; then
	echo "usage: jonjextdist <extension> <version>";
	exit 1
fi

jonjize=`jonj-config --prefix`/bin/jonjize
distname="$1-$2"

if test ! -f Makefile.in || test ! -f config.m4; then
	echo "Did not find required files in current directory"
	exit 1
fi

rm -rf modules *.lo *.o *.la config.status config.cache \
config.log libtool jonj_config.h config_vars.mk Makefile

myname=`basename \`pwd\``
cd ..
cp -rp $myname $distname
cd $distname
$jonjize
cd ..
tar cf $distname.tar $distname
rm -rf $distname $distname.tar.*
gzip --best $distname.tar
mv $distname.tar.gz $myname
